##	Friendly YAML Configuration File
##	Revised 7 March 2007 - David Demaree

# The items in this file are available throughout Friendly.
# For example, the item below is available in any controller
# as $GLOBALS['cfg']['application_title], or in any template
# as {$cfg.application_title}

application_title: My Awesome Friendly App
template_engine:   smarty


# You can put any variables you want in here, and some are
# used by Friendly to enable and/or configure certain
# features. The most common "magic" config items are listed
# below, and you can find a full list with explanations by
# visiting <http://friendlyphp.org/docs/reference/config>


# DATABASE SETTINGS: Friendly is designed to use a single database
# by default, containing all tables and rows to be used by this
# application. To enable database access for this Friendly app
# just edit the settings below to match your environment.

db:
   adapter: mysql
   host: localhost
   database: friendly
   username: root
   password:
       
      
# TEMPLATE COMPILE FOLDER: Friendly uses Smarty, a popular
# compiling template engine, to generate the HTML for your
# application. Smarty needs to compiles your templates into
# executable PHP code. By default, Friendly uses your server's
# /tmp directory for compiled templates. It will also automat-
# ically use the `cache` directory inside your Friendly app
# folder if it's writeable by PHP. If you cannot write to /tmp
# on your server, you must either make the `cache` folder
# writeable or specify another writeable directory using the
# compile_dir config option below.
# 
# compile_dir: cache/

# SESSION SETTINGS: By default Friendly stores session data in a MySQL
# database called `_friendly_sessions`. You can disable DB sessions by
# changing the `storage_method` key below to any value besides 'db'.

session:
   storage_method: db
   name: FRIENDLY_SESS
   expires: 86400
   path: /
   


# ENVIRONMENTS: Friendly can load in additional configuration
# settings specific to a given server environment.
# For more information about environments, visit
# <http://friendlyphp.org/docs/reference/environments>
# 
# To use an environment file called production.yml, just set the
# `environment` directive below to 'production' and uncomment it.
#
# environment: development